cache:
  untracked: true
  key: "$AWS_BUCKET_NAME"
  paths:
    - node_modules/

stages:
  - build
  - deploy

build-dev:  
   image: node:10.15.0 
   stage: build
   only:    
      - master  
   script:
      - export NODE_ENV=development
      - yarn
      - yarn build 
   artifacts:    
      paths:
         - dist/    
      expire_in: 1 hour
      
deploy-dev:
   cache: {}
   image: xueshanf/awscli
   stage: deploy
   only:    
      - master  
   script:  
      - aws s3 sync ./dist s3://$AWS_BUCKET_NAME/ --acl public-read --delete --follow-symlinks
build-prod:  
   image: lllelll/node_pupeeteer_bzip2_tar 
   stage: build
   only:    
      - release  
   script:
      - yarn
      - yarn build 
   artifacts:    
      paths:
         - dist/    
      expire_in: 1 hour
deploy-prod:  
   image: cptponk/git-ftp 
   cache: {}
   stage: deploy  
   only:    
      - release  
   script:    
      - git ftp push --auto-init --user $FTP_USERNAME --passwd $FTP_PASSWORD --syncroot dist/  "ftp://$FTP_SERVER_AND_FOLDER"  